# Generated by Django 4.1.5 on 2023-01-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dexterity", models.IntegerField(verbose_name="Ловкость")),
                ("strenght", models.IntegerField(verbose_name="Сила")),
                ("constitution", models.IntegerField(verbose_name="Телосложение")),
                ("intelligence", models.IntegerField(verbose_name="Интеллект")),
                ("wisdom", models.IntegerField(verbose_name="Мудрость")),
                ("charisma", models.IntegerField(verbose_name="Харизма")),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
    ]
