# Generated by Django 4.1.5 on 2023-01-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_abilities_race"),
        ("create_char", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Char",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_name",
                    models.CharField(max_length=30, verbose_name="Имя персонажа"),
                ),
                (
                    "char_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="base.classes",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "char_race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="base.races",
                        verbose_name="Раса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
            },
        ),
        migrations.AddField(
            model_name="stat",
            name="character",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="create_char.char",
                verbose_name="Характеристики персонажа",
            ),
            preserve_default=False,
        ),
    ]
