# Generated by Django 4.1.5 on 2023-01-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_char", "0002_char_stat_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="char",
            name="char_disc",
            field=models.TextField(default=1, verbose_name="Описание персонажа"),
            preserve_default=False,
        ),
    ]
