# Generated by Django 4.1.5 on 2023-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_char", "0003_char_char_disc"),
    ]

    operations = [
        migrations.AddField(
            model_name="char",
            name="char_history",
            field=models.TextField(default=1, verbose_name="История персонажа"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="char",
            name="char_disc",
            field=models.TextField(verbose_name="Описание внешности персонажа"),
        ),
    ]
