# Generated by Django 4.1.5 on 2023-01-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("create_char", "0004_char_char_history_alter_char_char_disc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="char",
            old_name="char_disc",
            new_name="char_view",
        ),
    ]
