# Generated by Django 4.1.5 on 2023-01-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(max_length=30, verbose_name="Название класса"),
                ),
                ("class_description", models.TextField(verbose_name="Описание")),
                (
                    "class_dice",
                    models.CharField(max_length=10, verbose_name="Кость хитов"),
                ),
                (
                    "class_mainstat",
                    models.CharField(
                        max_length=40, verbose_name="Основная характеристика"
                    ),
                ),
                (
                    "class_saving_throws",
                    models.CharField(
                        max_length=40, verbose_name="Владение спасбросками"
                    ),
                ),
                (
                    "class_equipment",
                    models.TextField(verbose_name="Владение доспехами и оружием"),
                ),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
            },
        ),
        migrations.CreateModel(
            name="Spells",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spell_name",
                    models.CharField(max_length=50, verbose_name="Название заклинания"),
                ),
                ("spell_lvl", models.IntegerField(verbose_name="Уровень заклинания")),
                (
                    "spell_duration",
                    models.CharField(max_length=50, verbose_name="Длительность"),
                ),
                (
                    "spell_range",
                    models.CharField(max_length=50, verbose_name="Дистанция"),
                ),
                (
                    "spell_component",
                    models.CharField(max_length=100, verbose_name="Компоненты"),
                ),
                ("spell_school", models.CharField(max_length=20, verbose_name="Школа")),
                (
                    "spell_timecast",
                    models.CharField(max_length=50, verbose_name="Время накладывания"),
                ),
                (
                    "spell_description",
                    models.TextField(verbose_name="Описание заклинания"),
                ),
                (
                    "spell_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.classes",
                        verbose_name="Доступный класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заклинание",
                "verbose_name_plural": "Заклинания",
            },
        ),
    ]
