# Generated by Django 4.1.5 on 2023-01-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trinkets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dice", models.IntegerField(verbose_name="d100")),
                ("value", models.TextField(verbose_name="Безделушка")),
            ],
            options={
                "verbose_name": "Безделушка",
                "verbose_name_plural": "Безделушки",
            },
        ),
    ]
