# Generated by Django 4.1.5 on 2023-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_trinkets_options_alter_trinkets_dice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_name",
                    models.CharField(max_length=20, verbose_name="Характеристика"),
                ),
                (
                    "stat_description",
                    models.CharField(max_length=100, verbose_name="Показатель"),
                ),
                (
                    "stat_main",
                    models.CharField(max_length=100, verbose_name="Важно для"),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.AlterModelOptions(
            name="spells",
            options={
                "ordering": ["spell_class", "spell_lvl", "spell_name"],
                "verbose_name": "Заклинание",
                "verbose_name_plural": "Заклинания",
            },
        ),
    ]
