# Generated by Django 4.1.5 on 2023-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_stats_alter_spells_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_name",
                    models.CharField(max_length=100, verbose_name="Состояние"),
                ),
                ("condition_description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Состояние",
                "verbose_name_plural": "Состояния",
            },
        ),
    ]
