# Generated by Django 4.1.5 on 2023-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_conditions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conditions",
            options={
                "ordering": ["condition_name"],
                "verbose_name": "Состояние",
                "verbose_name_plural": "Состояния",
            },
        ),
        migrations.CreateModel(
            name="Creatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creature_name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "creature_description",
                    models.CharField(max_length=100, verbose_name="Описание"),
                ),
                (
                    "creature_armor",
                    models.CharField(max_length=100, verbose_name="Класс доспеха"),
                ),
                ("creature_hits", models.CharField(max_length=30, verbose_name="Хиты")),
                (
                    "creature_speed",
                    models.CharField(max_length=100, verbose_name="Скорость"),
                ),
                (
                    "creature_stats",
                    models.CharField(max_length=100, verbose_name="Характеристики"),
                ),
                (
                    "creature_abilities",
                    models.CharField(max_length=100, verbose_name="Навыки"),
                ),
                (
                    "creature_specs",
                    models.CharField(max_length=100, verbose_name="Чувства"),
                ),
                (
                    "creature_languages",
                    models.CharField(blank=True, max_length=100, verbose_name="Языки"),
                ),
                (
                    "creature_danger",
                    models.CharField(max_length=100, verbose_name="Опасность"),
                ),
                ("creature_skills", models.TextField(verbose_name="Способности")),
                ("creature_actions", models.TextField(verbose_name="Действия")),
                (
                    "creature_conditions",
                    models.ManyToManyField(
                        to="base.conditions", verbose_name="Состояния"
                    ),
                ),
            ],
            options={
                "verbose_name": "Существо",
                "verbose_name_plural": "Существа",
            },
        ),
    ]
