# Generated by Django 4.1.5 on 2023-01-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_conditions_options_creatures"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionsPositive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_name",
                    models.CharField(max_length=100, verbose_name="Состояние"),
                ),
                ("condition_description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Положительное состояние",
                "verbose_name_plural": "Положительные состояния",
                "ordering": ["condition_name"],
            },
        ),
        migrations.AlterField(
            model_name="creatures",
            name="creature_conditions",
            field=models.ManyToManyField(
                to="base.conditionspositive", verbose_name="Состояния"
            ),
        ),
    ]
