# Generated by Django 4.1.5 on 2023-01-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_conditionspositive_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creatures",
            options={
                "ordering": ["creature_name"],
                "verbose_name": "Существо",
                "verbose_name_plural": "Существа",
            },
        ),
        migrations.RemoveField(
            model_name="creatures",
            name="creature_conditions",
        ),
        migrations.AddField(
            model_name="creatures",
            name="creature_conditions",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Состояния"
            ),
        ),
    ]
