# Generated by Django 4.1.5 on 2023-01-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_creatures_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConditionsPositive",
        ),
    ]
