# Generated by Django 4.1.5 on 2023-01-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_delete_conditionspositive"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Особенность")),
                ("content", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Особенность",
                "verbose_name_plural": "Особенности",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="RaceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Раса")),
            ],
            options={
                "verbose_name": "Список рас",
                "verbose_name_plural": "Список рас",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Races",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race_name",
                    models.CharField(
                        max_length=100, verbose_name="Раса + разновидность"
                    ),
                ),
                ("race_description", models.TextField(verbose_name="Описание")),
                ("race_names", models.TextField(verbose_name="Имена")),
                (
                    "race_stats",
                    models.CharField(
                        max_length=100, verbose_name="Увеличение характеристик"
                    ),
                ),
                ("race_age", models.TextField(verbose_name="Возраст")),
                ("race_worldview", models.TextField(verbose_name="Мировоззрение")),
                ("race_size", models.TextField(verbose_name="Размер")),
                (
                    "race_abilities",
                    models.ManyToManyField(
                        to="base.abilities", verbose_name="Особенности"
                    ),
                ),
                (
                    "race_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.racelist",
                        verbose_name="Раса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расы",
                "verbose_name_plural": "Раса",
                "ordering": ["race_family", "race_name"],
            },
        ),
    ]
