# Generated by Django 4.1.5 on 2023-01-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_races_race_speed_alter_races_race_abilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="races",
            name="race_language",
            field=models.TextField(blank=True, verbose_name="Языки"),
        ),
    ]
