# Generated by Django 4.1.5 on 2023-01-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_races_race_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abilities",
            options={
                "ordering": ["race", "title"],
                "verbose_name": "Особенность",
                "verbose_name_plural": "Особенности",
            },
        ),
        migrations.AddField(
            model_name="abilities",
            name="race",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.racelist",
                verbose_name="К расе",
            ),
        ),
    ]
