# Generated by Django 4.1.5 on 2023-01-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_abilities_options_abilities_race"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abilities",
            name="race",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.racelist",
                verbose_name="К расе",
            ),
            preserve_default=False,
        ),
    ]
